version: '3.8'

services:
  research-system:
    build:
      context: .
      dockerfile: Dockerfile
    image: research-system:latest
    container_name: research-system
    ports:
      - "8181:8181"
    environment:
      - DB_USE_POSTGRES=true
      - DB_POSTGRES_HOST=postgres
      - DB_POSTGRES_PORT=5432
      - DB_POSTGRES_DBNAME=research
      - DB_POSTGRES_USER=postgres
      - DB_POSTGRES_PASSWORD=postgres-password
      - DEBUG=true
      - LOG_LEVEL=debug
    volumes:
      - ./:/app
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8181/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  postgres:
    image: postgres:16
    container_name: research-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=research
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres-password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  postgres-data: