services:
  postgres:
    image: postgres:16
    container_name: research-postgres-test
    environment:
      - POSTGRES_DB=research
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres-password
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  test-pg:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: research-system-test-pg
    environment:
      - DB_USE_POSTGRES=true
      - DATABASE_URL=postgresql://postgres:postgres-password@postgres:5432/research
      - DEBUG=true
      - LOG_LEVEL=debug
    volumes:
      - ./test_postgres.py:/app/test_postgres.py
    depends_on:
      postgres:
        condition: service_healthy
    command: ["bash", "-c", "sleep 5 && python test_postgres.py"]