apiVersion: v1
kind: ConfigMap
metadata:
  name: research-system-config
data:
  config.yaml: |
    database:
      use_postgres: true
      postgres:
        host: postgres
        port: 5432
        dbname: research
        user: postgres
        connect_timeout: 5
        retry_attempts: 3
  
  # Application settings
  app.env: |
    DEBUG=false
    LOG_LEVEL=info
    SERVER_HOST=0.0.0.0
    SERVER_PORT=8181
    API_TIMEOUT=30
    CORS_ORIGINS=*