apiVersion: apps/v1
kind: Deployment
metadata:
  name: research-system
  labels:
    app: research-system
    app.kubernetes.io/name: research-system
    app.kubernetes.io/version: "${RESEARCH_SYSTEM_VERSION:-1.0.0}"
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: research-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: research-system
  template:
    metadata:
      labels:
        app: research-system
    spec:
      initContainers:
      - name: wait-for-ollama
        image: busybox:1.28
        command: ['sh', '-c', 'until wget -q -O - http://ollama-service:11434/api/version; do echo "Waiting for Ollama service..."; sleep 2; done;']
      containers:
      - name: research-system
        image: ${RESEARCH_SYSTEM_IMAGE:-research-system:latest}
        imagePullPolicy: IfNotPresent
        env:
        - name: RESEARCH_SYSTEM_VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels.app.kubernetes.io/version
        - name: CONFIG_PATH
          value: "/app/config/config.yaml"
        - name: RESEARCH_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: research-system-db-credentials
              key: DB_POSTGRES_PASSWORD
        # Optional: override specific environment variables
        - name: RESEARCH_ENV_MODE
          value: "production"
        envFrom:
        - configMapRef:
            name: research-system-env
        ports:
        - containerPort: 8181
        resources:
          limits:
            cpu: "1000m"
            memory: "1Gi"
          requests:
            cpu: "200m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8181
          initialDelaySeconds: 10
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8181
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
      volumes:
      - name: config-volume
        configMap:
          name: research-system-config