---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-data
  namespace: research-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ollama-config
  namespace: research-system
data:
  DEFAULT_MODELS: "gemma3:1b"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: research-system
  labels:
    app: ollama
    component: llm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
        component: llm
    spec:
      containers:
      - name: ollama
        image: ollama/ollama:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "Starting Ollama server at $(date)"
            if [ -n "$DEFAULT_MODELS" ]; then
              echo "Pulling default models: $DEFAULT_MODELS"
              for model in $(echo $DEFAULT_MODELS | tr "," " "); do
                echo "Pulling model: $model"
                ollama pull $model &
              done
              wait
            fi
            OLLAMA_HOST=0.0.0.0 exec ollama serve
        ports:
        - containerPort: 11434
          name: http
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
        volumeMounts:
        - name: ollama-data
          mountPath: /root/.ollama
        env:
        - name: DEFAULT_MODELS
          valueFrom:
            configMapKeyRef:
              name: ollama-config
              key: DEFAULT_MODELS
        readinessProbe:
          httpGet:
            path: /api/version
            port: 11434
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/version
            port: 11434
          initialDelaySeconds: 30
          periodSeconds: 20
      volumes:
      - name: ollama-data
        persistentVolumeClaim:
          claimName: ollama-data
---
apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: research-system
  labels:
    app: ollama
    component: llm
spec:
  selector:
    app: ollama
  ports:
  - port: 11434
    targetPort: 11434
    protocol: TCP
    name: http
  type: ClusterIP