apiVersion: v1
kind: Secret
metadata:
  name: research-system-db-credentials
type: Opaque
stringData:
  DB_POSTGRES_PASSWORD: postgres-password
  # Note: In a real production environment, this should be managed through a proper secret management system
  # and not committed to the repository.