apiVersion: v1
kind: Service
metadata:
  name: research-system
  labels:
    app: research-system
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8181
    protocol: TCP
    name: http
  selector:
    app: research-system